site_url: 'https://icos-carbon-portal.github.io/fileshare/'

site_name: ICOS Fileshare Documentation
nav:
    - About: index.md
    - Creating your account: creating_account.md
    - Becoming familiar with ICOS Fileshare: becoming_familiar.md
    - Managing your data: managing_data.md
    - Sharing your data: sharing_data.md
    - Advanced functions: advanced_functions.md

theme:
    name: readthedocs

extra_css:
    - style.css

markdown_extensions:
    - admonition