INHERIT: ../mkdocs_base.yml
site_url: 'https://icos-carbon-portal.github.io/'
edit_uri: 'blob/master/icos-carbon-portal.github.io/docs/'

site_name: ICOS Carbon Portal Documentation Hub
nav:
    - index.md

extra_css:
    - style.css