site_url: 'https://icos-carbon-portal.github.io/'

site_name: ICOS Carbon Portal Documentation Hub
nav:
    - index.md

theme:
    name: readthedocs

extra_css:
    - style.css

markdown_extensions:
    - admonition