site_url: 'https://icos-carbon-portal.github.io/fileshare/'

site_name: ICOS Fileshare Documentation
nav:
    - About: index.md
    - creating_account.md
    - becoming_familiar.md
    - enable_2fa.md
    - managing_data.md
    - sharing_data.md
    - advanced_functions.md

theme:
    name: readthedocs

extra_css:
    - style.css

markdown_extensions:
    - admonition
    - sane_lists