INHERIT: ../mkdocs_base.yml
site_url: 'https://icos-carbon-portal.github.io/fileshare/'
edit_uri: 'blob/master/fileshare/docs/'

site_name: ICOS Fileshare Documentation
nav:
    - About: index.md
    - creating_account.md
    - becoming_familiar.md
    - enable_2fa.md
    - managing_data.md
    - sharing_data.md
    - calendar.md
    - advanced_functions.md

extra_css:
    - style.css